site_name: PyNest

site_url: https://PyNest.github.io/PyNest/

theme:
  name: material
  features:
    - content.code.copy

plugins:
- search
- mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Overview: index.md
  - Usage:
      - Blank Application: blank.md
      - Sync ORM Application: sync_orm.md
      - Async ORM Application: async_orm.md
      - MongoDB Application: mongodb.md
  - API Reference:
    - Modules: decorators/module.md
    - Controllers: decorators/controller.md
    - Services: decorators/service.md
    - Utils: decorators/utils.md
    - Core: api.md
    - database: database.md

  - License: license.md
