name: Deploy Docs

on: [workflow_call, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy_docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy License File
        run: cp LICENSE docs/license.md

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.7"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --no-dev --group docs

      - name: Build docs
        run: uv run mkdocs build --clean

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
